"""Pydantic schemas for API validation."""

from app.schemas.vendor import (
    VendorCreate,
    VendorUpdate,
    VendorResponse,
    VendorListResponse,
    VendorCategoryCreate,
    VendorCategoryUpdate,
    VendorCategoryResponse,
    VendorCertificationCreate,
    VendorCertificationUpdate,
    VendorCertificationResponse,
    VendorContactCreate,
    VendorContactUpdate,
    VendorContactResponse,
    VendorRatingCreate,
    VendorRatingUpdate,
    VendorRatingResponse,
    VendorFilterParams,
)
from app.schemas.rfq import (
    RFQCreate,
    RFQUpdate,
    RFQResponse,
    RFQListResponse,
    RFQItemCreate,
    RFQItemUpdate,
    RFQItemResponse,
    RFQVendorInvitationCreate,
    RFQVendorInvitationResponse,
    QuotationCreate,
    QuotationUpdate,
    QuotationResponse,
    QuotationItemCreate,
    QuotationItemUpdate,
    QuotationItemResponse,
    QuoteComparisonResponse,
    RFQFilterParams,
    RFQStatusUpdate,
)

__all__ = [
    # Vendor schemas
    "VendorCreate",
    "VendorUpdate",
    "VendorResponse",
    "VendorListResponse",
    "VendorCategoryCreate",
    "VendorCategoryUpdate",
    "VendorCategoryResponse",
    "VendorCertificationCreate",
    "VendorCertificationUpdate",
    "VendorCertificationResponse",
    "VendorContactCreate",
    "VendorContactUpdate",
    "VendorContactResponse",
    "VendorRatingCreate",
    "VendorRatingUpdate",
    "VendorRatingResponse",
    "VendorFilterParams",
    # RFQ schemas
    "RFQCreate",
    "RFQUpdate",
    "RFQResponse",
    "RFQListResponse",
    "RFQItemCreate",
    "RFQItemUpdate",
    "RFQItemResponse",
    "RFQVendorInvitationCreate",
    "RFQVendorInvitationResponse",
    "QuotationCreate",
    "QuotationUpdate",
    "QuotationResponse",
    "QuotationItemCreate",
    "QuotationItemUpdate",
    "QuotationItemResponse",
    "QuoteComparisonResponse",
    "RFQFilterParams",
    "RFQStatusUpdate",
]
