import {
  RFQ,
  Vendor,
  EquipmentData,
  DashboardStats,
  ActivityItem,
  VendorComparison,
  GanttTask,
  EquipmentType
} from '../types';

// Mock RFQ data
export const mockRFQs: RFQ[] = [
  {
    id: '1',
    rfq_number: 'RFQ-2024-001',
    title: 'DSC Equipment Procurement',
    description: 'Differential Scanning Calorimeter for thermal analysis lab',
    status: 'open',
    issue_date: '2024-01-15',
    closing_date: '2024-02-15',
    currency: 'USD',
    estimated_value: 85000,
    project_number: 'PRJ-2024-001',
    project_name: 'Lab Equipment Upgrade',
    item_count: 3,
    quotation_count: 4,
    created_at: '2024-01-15T10:00:00Z',
    equipment_type: 'DSC',
  },
  {
    id: '2',
    rfq_number: 'RFQ-2024-002',
    title: 'TGA System Acquisition',
    description: 'Thermogravimetric Analyzer for material characterization',
    status: 'open',
    issue_date: '2024-01-18',
    closing_date: '2024-02-20',
    currency: 'USD',
    estimated_value: 120000,
    project_number: 'PRJ-2024-001',
    project_name: 'Lab Equipment Upgrade',
    item_count: 2,
    quotation_count: 3,
    created_at: '2024-01-18T14:30:00Z',
    equipment_type: 'TGA',
  },
  {
    id: '3',
    rfq_number: 'RFQ-2024-003',
    title: 'Environmental Chamber Purchase',
    description: 'Climate test chamber for stability testing',
    status: 'closed',
    issue_date: '2024-01-10',
    closing_date: '2024-02-01',
    currency: 'USD',
    estimated_value: 65000,
    project_number: 'PRJ-2024-002',
    project_name: 'Quality Control Lab',
    item_count: 1,
    quotation_count: 5,
    created_at: '2024-01-10T09:00:00Z',
    equipment_type: 'Chamber',
  },
  {
    id: '4',
    rfq_number: 'RFQ-2024-004',
    title: 'UV-Vis Spectrometer',
    description: 'Spectrophotometer for analytical chemistry',
    status: 'awarded',
    issue_date: '2024-01-05',
    closing_date: '2024-01-25',
    currency: 'USD',
    estimated_value: 45000,
    project_number: 'PRJ-2024-003',
    project_name: 'Research Lab Setup',
    item_count: 2,
    quotation_count: 4,
    created_at: '2024-01-05T11:00:00Z',
    equipment_type: 'Spectrometer',
  },
  {
    id: '5',
    rfq_number: 'RFQ-2024-005',
    title: 'HPLC System',
    description: 'High-Performance Liquid Chromatograph',
    status: 'draft',
    issue_date: undefined,
    closing_date: undefined,
    currency: 'USD',
    estimated_value: 95000,
    project_number: 'PRJ-2024-003',
    project_name: 'Research Lab Setup',
    item_count: 4,
    quotation_count: 0,
    created_at: '2024-01-20T16:00:00Z',
    equipment_type: 'Chromatograph',
  },
];

// Mock Vendors
export const mockVendors: Vendor[] = [
  {
    id: '1',
    vendor_code: 'VND-001',
    company_name: 'TA Instruments',
    contact_person: 'John Smith',
    email: 'john.smith@tainstruments.com',
    phone: '+1-302-555-0123',
    city: 'New Castle',
    country: 'USA',
    is_approved: true,
    rating: 4.8,
    created_at: '2023-06-15T10:00:00Z',
  },
  {
    id: '2',
    vendor_code: 'VND-002',
    company_name: 'Mettler Toledo',
    contact_person: 'Sarah Johnson',
    email: 'sarah.johnson@mt.com',
    phone: '+1-614-555-0456',
    city: 'Columbus',
    country: 'USA',
    is_approved: true,
    rating: 4.7,
    created_at: '2023-05-20T14:00:00Z',
  },
  {
    id: '3',
    vendor_code: 'VND-003',
    company_name: 'PerkinElmer',
    contact_person: 'Michael Brown',
    email: 'michael.brown@perkinelmer.com',
    phone: '+1-781-555-0789',
    city: 'Waltham',
    country: 'USA',
    is_approved: true,
    rating: 4.6,
    created_at: '2023-04-10T09:00:00Z',
  },
  {
    id: '4',
    vendor_code: 'VND-004',
    company_name: 'Netzsch',
    contact_person: 'Hans Mueller',
    email: 'hans.mueller@netzsch.com',
    phone: '+49-9281-555-012',
    city: 'Selb',
    country: 'Germany',
    is_approved: true,
    rating: 4.5,
    created_at: '2023-07-01T11:00:00Z',
  },
  {
    id: '5',
    vendor_code: 'VND-005',
    company_name: 'Shimadzu',
    contact_person: 'Yuki Tanaka',
    email: 'yuki.tanaka@shimadzu.com',
    phone: '+81-75-555-3456',
    city: 'Kyoto',
    country: 'Japan',
    is_approved: true,
    rating: 4.9,
    created_at: '2023-03-15T08:00:00Z',
  },
];

// Mock Equipment Data (parsed from Excel)
export const mockEquipmentData: EquipmentData[] = [
  {
    id: '1',
    equipment: 'Discovery DSC 250',
    equipment_type: 'DSC',
    vendor: 'TA Instruments',
    vendor_id: '1',
    technical_specs: {
      model: 'Discovery DSC 250',
      manufacturer: 'TA Instruments',
      specifications: [
        'Temperature range: -180°C to 725°C',
        'Sensitivity: 0.2 µW',
        'Resolution: 0.01°C',
        'Autosampler: 50 positions',
      ],
      features: ['Tzero technology', 'Modulated DSC', 'TRIOS software'],
      warranty_months: 24,
    },
    price: 78500,
    currency: 'USD',
    timeline: {
      lead_time_days: 45,
      delivery_date: '2024-03-15',
      installation_days: 3,
      training_days: 2,
    },
    tbe_score: {
      overall: 92,
      technical: 95,
      commercial: 88,
      delivery: 90,
      compliance: 94,
      rank: 1,
    },
    compliance_status: 'compliant',
  },
  {
    id: '2',
    equipment: 'DSC 3+',
    equipment_type: 'DSC',
    vendor: 'Mettler Toledo',
    vendor_id: '2',
    technical_specs: {
      model: 'DSC 3+',
      manufacturer: 'Mettler Toledo',
      specifications: [
        'Temperature range: -150°C to 700°C',
        'Sensitivity: 0.1 µW',
        'Resolution: 0.01°C',
        'Autosampler: 34 positions',
      ],
      features: ['FRS 6+ sensor', 'MultiSTAR sensors', 'STARe software'],
      warranty_months: 24,
    },
    price: 82000,
    currency: 'USD',
    timeline: {
      lead_time_days: 60,
      delivery_date: '2024-03-25',
      installation_days: 2,
      training_days: 2,
    },
    tbe_score: {
      overall: 88,
      technical: 92,
      commercial: 82,
      delivery: 85,
      compliance: 92,
      rank: 2,
    },
    compliance_status: 'compliant',
  },
  {
    id: '3',
    equipment: 'DSC 8500',
    equipment_type: 'DSC',
    vendor: 'PerkinElmer',
    vendor_id: '3',
    technical_specs: {
      model: 'DSC 8500',
      manufacturer: 'PerkinElmer',
      specifications: [
        'Temperature range: -180°C to 750°C',
        'Sensitivity: 0.2 µW',
        'Resolution: 0.005°C',
        'HyperDSC capability',
      ],
      features: ['HyperDSC', 'StepScan DSC', 'Pyris software'],
      warranty_months: 12,
    },
    price: 75000,
    currency: 'USD',
    timeline: {
      lead_time_days: 30,
      delivery_date: '2024-03-01',
      installation_days: 2,
      training_days: 1,
    },
    tbe_score: {
      overall: 85,
      technical: 88,
      commercial: 90,
      delivery: 78,
      compliance: 82,
      rank: 3,
    },
    compliance_status: 'partial',
  },
  {
    id: '4',
    equipment: 'TGA 550',
    equipment_type: 'TGA',
    vendor: 'TA Instruments',
    vendor_id: '1',
    technical_specs: {
      model: 'TGA 550',
      manufacturer: 'TA Instruments',
      specifications: [
        'Temperature range: RT to 1000°C',
        'Balance precision: 0.01 µg',
        'Heating rate: 0.1 to 100°C/min',
        'Sample capacity: 1g',
      ],
      features: ['IR furnace', 'Hi-Res TGA', 'TRIOS software'],
      warranty_months: 24,
    },
    price: 115000,
    currency: 'USD',
    timeline: {
      lead_time_days: 50,
      delivery_date: '2024-03-20',
      installation_days: 2,
      training_days: 2,
    },
    tbe_score: {
      overall: 94,
      technical: 96,
      commercial: 90,
      delivery: 92,
      compliance: 96,
      rank: 1,
    },
    compliance_status: 'compliant',
  },
  {
    id: '5',
    equipment: 'TGA/DSC 3+',
    equipment_type: 'TGA',
    vendor: 'Mettler Toledo',
    vendor_id: '2',
    technical_specs: {
      model: 'TGA/DSC 3+',
      manufacturer: 'Mettler Toledo',
      specifications: [
        'Temperature range: RT to 1100°C',
        'Balance precision: 0.1 µg',
        'Heating rate: 0.02 to 250°C/min',
        'Sample capacity: 5g',
      ],
      features: ['Simultaneous TGA/DSC', 'Ultra-micro balance', 'STARe software'],
      warranty_months: 24,
    },
    price: 125000,
    currency: 'USD',
    timeline: {
      lead_time_days: 55,
      delivery_date: '2024-03-28',
      installation_days: 3,
      training_days: 2,
    },
    tbe_score: {
      overall: 91,
      technical: 94,
      commercial: 85,
      delivery: 90,
      compliance: 94,
      rank: 2,
    },
    compliance_status: 'compliant',
  },
  {
    id: '6',
    equipment: 'Climate Chamber MK 240',
    equipment_type: 'Chamber',
    vendor: 'Memmert',
    vendor_id: '6',
    technical_specs: {
      model: 'MK 240',
      manufacturer: 'Memmert',
      specifications: [
        'Temperature range: -40°C to +180°C',
        'Humidity range: 10% to 98% RH',
        'Volume: 240 liters',
        'Temperature uniformity: ±0.5°C',
      ],
      features: ['AtmoCONTROL software', 'USB interface', 'Data logging'],
      warranty_months: 24,
    },
    price: 58000,
    currency: 'USD',
    timeline: {
      lead_time_days: 40,
      delivery_date: '2024-03-10',
      installation_days: 1,
      training_days: 1,
    },
    tbe_score: {
      overall: 87,
      technical: 90,
      commercial: 88,
      delivery: 82,
      compliance: 88,
      rank: 1,
    },
    compliance_status: 'compliant',
  },
];

// Mock Dashboard Stats
export const mockDashboardStats: DashboardStats = {
  active_projects: 5,
  open_rfqs: 8,
  active_pos: 12,
  approved_vendors: 24,
  total_po_value: 485000,
  recent_quotations: 15,
};

// Mock Activity Feed
export const mockActivityFeed: ActivityItem[] = [
  {
    id: '1',
    type: 'quotation_received',
    title: 'New Quotation Received',
    description: 'TA Instruments submitted quotation for RFQ-2024-001',
    timestamp: '2024-01-22T14:30:00Z',
    entity_id: 'Q-001',
    entity_type: 'quotation',
    user: 'System',
  },
  {
    id: '2',
    type: 'tbe_completed',
    title: 'TBE Evaluation Completed',
    description: 'Technical bid evaluation completed for RFQ-2024-004',
    timestamp: '2024-01-22T11:00:00Z',
    entity_id: 'TBE-001',
    entity_type: 'tbe_evaluation',
    user: 'John Doe',
  },
  {
    id: '3',
    type: 'po_issued',
    title: 'Purchase Order Issued',
    description: 'PO-2024-015 issued to Shimadzu for UV-Vis Spectrometer',
    timestamp: '2024-01-21T16:45:00Z',
    entity_id: 'PO-015',
    entity_type: 'purchase_order',
    user: 'Jane Smith',
  },
  {
    id: '4',
    type: 'rfq_created',
    title: 'New RFQ Created',
    description: 'RFQ-2024-005 created for HPLC System procurement',
    timestamp: '2024-01-20T09:15:00Z',
    entity_id: 'RFQ-005',
    entity_type: 'rfq',
    user: 'Mike Johnson',
  },
  {
    id: '5',
    type: 'vendor_approved',
    title: 'Vendor Approved',
    description: 'Netzsch approved as qualified vendor',
    timestamp: '2024-01-19T13:20:00Z',
    entity_id: 'VND-004',
    entity_type: 'vendor',
    user: 'Admin',
  },
];

// Mock Vendor Comparison Data
export const mockVendorComparisons: VendorComparison[] = [
  {
    vendor_id: '1',
    vendor_name: 'TA Instruments',
    equipment_type: 'DSC',
    total_price: 78500,
    average_tbe_score: 92,
    technical_score: 95,
    delivery_score: 90,
    compliance_score: 94,
    items_quoted: 3,
    items: mockEquipmentData.filter(e => e.vendor_id === '1'),
  },
  {
    vendor_id: '2',
    vendor_name: 'Mettler Toledo',
    equipment_type: 'DSC',
    total_price: 82000,
    average_tbe_score: 88,
    technical_score: 92,
    delivery_score: 85,
    compliance_score: 92,
    items_quoted: 2,
    items: mockEquipmentData.filter(e => e.vendor_id === '2'),
  },
  {
    vendor_id: '3',
    vendor_name: 'PerkinElmer',
    equipment_type: 'DSC',
    total_price: 75000,
    average_tbe_score: 85,
    technical_score: 88,
    delivery_score: 78,
    compliance_score: 82,
    items_quoted: 2,
    items: mockEquipmentData.filter(e => e.vendor_id === '3'),
  },
];

// Mock Gantt Tasks
export const mockGanttTasks: GanttTask[] = [
  {
    id: '1',
    name: 'DSC Equipment - TA Instruments',
    equipment_type: 'DSC',
    vendor: 'TA Instruments',
    start_date: '2024-02-01',
    end_date: '2024-03-15',
    progress: 25,
    status: 'in_progress',
  },
  {
    id: '2',
    name: 'TGA System - Mettler Toledo',
    equipment_type: 'TGA',
    vendor: 'Mettler Toledo',
    start_date: '2024-02-15',
    end_date: '2024-04-01',
    progress: 10,
    status: 'pending',
  },
  {
    id: '3',
    name: 'Climate Chamber - Memmert',
    equipment_type: 'Chamber',
    vendor: 'Memmert',
    start_date: '2024-01-25',
    end_date: '2024-03-10',
    progress: 45,
    status: 'in_progress',
  },
  {
    id: '4',
    name: 'UV-Vis Spectrometer - Shimadzu',
    equipment_type: 'Spectrometer',
    vendor: 'Shimadzu',
    start_date: '2024-01-15',
    end_date: '2024-02-28',
    progress: 80,
    status: 'in_progress',
  },
  {
    id: '5',
    name: 'HPLC System - Agilent',
    equipment_type: 'Chromatograph',
    vendor: 'Agilent',
    start_date: '2024-03-01',
    end_date: '2024-04-30',
    progress: 0,
    status: 'pending',
  },
];

// Equipment types for filtering
export const equipmentTypes: EquipmentType[] = [
  'DSC',
  'TGA',
  'Chamber',
  'Spectrometer',
  'Chromatograph',
  'Microscope',
  'Analyzer',
  'Other',
];
